# Site settings

title: Elisabeth Laliberte De Gagne Portfolio
email: your-email@domain.com # Your contant emai  l

description: > # this means to ignore newlines until "baseurl:"
  Sont presentes sur ce site mes projets passes, presents et futures !
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://elildg.github.io/"

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     example  # Replace this with your Twitter username
github_username:      elildg
linkedin_username:    example  # Replace this with your LinkedIn username
google_plus_username: example  # Replace this with your Google+ username
facebook_username:    example  # Replace this with your Facebook username
dribbble_username:    example  # Replace this with your Dribbble username

# Build settings
markdown: kramdown
